const fs = require('fs');
const path = require('path');
const assert = require('assert');
let pass=0;
function ok(cond,msg){ if(!cond){ console.error('  ✗ '+msg); throw new assert.AssertionError({message:msg}); } pass++; }
const src=fs.readFileSync(path.join(__dirname,'..','server.js'),'utf8');
const provider=fs.readFileSync(path.join(__dirname,'..','cloudflare-domain-provider.js'),'utf8');
const reconciler=fs.readFileSync(path.join(__dirname,'..','domain-reconciler.js'),'utf8');
const edge=fs.readFileSync(path.join(__dirname,'..','edge-domain-auth.js'),'utf8');
const post=src.slice(src.indexOf("app.post('/api/domains'"),src.indexOf('// Guia de onboarding DNS'));
const del=src.slice(src.indexOf("app.delete('/api/domains/:host'"),src.indexOf("app.post('/api/domains/verify'"));
const verify=src.slice(src.indexOf("app.post('/api/domains/verify'"),src.indexOf("app.get('/api/custom-domains/:host/diagnostics'"));
const diag=src.slice(src.indexOf("app.get('/api/custom-domains/:host/diagnostics'"),src.indexOf('// ═══ Pushcut'));

ok(src.includes('function activeDomainProvider()'),'server define activeDomainProvider');
ok(/function activeDomainProvider\(\)[\s\S]*return cloudflareDomainProvider/.test(src),'novos domínios preferem Cloudflare sem fallback Railway');
ok(post.includes('cloudflareDomainProvider.health({ force: true })'),'POST exige health real antes de provisionar');
ok(!post.includes('railwayDomainProvider.register'),'POST nunca registra novo domínio no Railway');
ok(del.includes('providerForDomainEntry(found)'),'DELETE respeita provider persistido');
ok(verify.includes('providerForDomainEntry(registeredDomain)'),'verify respeita provider persistido');
ok(src.includes('cloudflareDomainProvider.cnameTarget()'),'API usa CNAME target SaaS');
ok(!post.includes('PUBLIC_APP_HOST'),'POST não instrui origem Railway');
ok(provider.includes("ssl: sslRequest(host)"),'Custom Hostname usa contrato SSL central');
ok(provider.includes("method: 'http'"),'DCV usa HTTP');
ok(provider.includes('cloudflare_branding = true'),'hostnames longos habilitam branding');
ok(provider.includes('codes.includes(1404)'),'provider trata SaaS não provisionado');
ok(provider.includes('codes.includes(1405)'),'provider trata quota');
ok(provider.includes('codes.includes(1406)'),'provider trata duplicado');
ok(provider.includes("status === 429"),'provider trata rate limit');
ok(provider.includes('retryAfterSeconds'),'provider preserva Retry-After');
ok(provider.includes('retriggerValidation'),'provider suporta retrigger DCV');
ok(reconciler.includes('retriggerValidation'),'reconciliador aciona retrigger quando DNS chega');
ok(reconciler.includes("p.name !== 'cloudflare' || !!(providerState && providerState.status === 'active'"),'active exige estado Cloudflare ativo');
ok(verify.includes('providerActiveForVerify'),'verify exige provider ativo para Cloudflare');
ok(src.includes('protectedDomains.isProtectedSaasHost(host)'),'hosts internos são bloqueados');
ok(src.includes("'domain_reserved'"),'backend retorna domain_reserved');
ok(edge.includes('timingSafeEqual'),'edge usa comparação timing-safe');
ok(edge.includes('MAX_SKEW_SECONDS'),'edge tem replay protection');
ok(diag.includes('providerForDomainEntry(entry)'),'diagnóstico usa provider do domínio');
ok(diag.includes('domainSecurity.tlsProbe') && diag.includes('__domain-check'),'diagnóstico exige TLS + prova HTTP');
console.log('\n[custom-domains-routes] '+pass+' asserts OK');
