'use strict'
const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')
const root = path.resolve(__dirname, '..')
const read = (p) => fs.readFileSync(path.join(root, p), 'utf8')

const creatives = read('dashboard/components/ads/catalog-creatives.tsx')
const quick = read('dashboard/components/ads/catalog-quick-campaigns-dialog.tsx')
const batch = read('dashboard/components/ads/catalog-batch-dialog.tsx')
const list = read('dashboard/components/ads/catalog-list.tsx')
const manager = read('dashboard/components/ads/catalog-manager.tsx')
const detail = read('dashboard/components/ads/catalog-detail.tsx')
const launcher = read('dashboard/components/ads/universal-launcher-dialog.tsx')
const smart = read('dashboard/components/ads/smart-plus-create-dialog.tsx')
const inbox = read('dashboard/components/ads/needs-you-inbox.tsx')
const automation = read('dashboard/components/ads/automation-panel.tsx')
const magic = read('dashboard/components/ads/magic-ops-panel.tsx')
const view = read('dashboard/components/ads/tiktok-ads-view.tsx')
const routes = read('ads-routes.js')
const overviewApi = read('dashboard/lib/api.ts')
const profitEngine = read('profit-engine.js')

// Remoção remota não contamina o estado de upload local.
const removeStart = creatives.indexOf('async function remove(')
const removeEnd = creatives.indexOf('\n  return (', removeStart)
const removeBody = creatives.slice(removeStart, removeEnd)
assert.ok(removeStart >= 0 && removeEnd > removeStart)
assert.doesNotMatch(removeBody, /onBusyChange\?\.\(true\)/)
assert.match(creatives, /async function upload\([\s\S]*onBusyChange\?\.\(true\)/)
assert.match(creatives, /onPendingChange\?\.\(pending\.length\)/)

// Product Link participa do guard e bloqueia fechamento durante upload.
assert.match(quick, /onLocalWorkStateChange\?: \(state: \{ uploading: boolean; pending: number \}\) => void/)
assert.match(quick, /localPendingCount = open \? creatives\.filter\(\(creative\) => creative\.status !== 'ready'\)\.length : 0/)
assert.match(quick, /onLocalWorkStateChange\?\.\(\{ uploading: open && uploading, pending: localPendingCount \}\)/)
assert.match(quick, /busy=\{busy \|\| uploading\}/)
assert.match(quick, /if \(!busy && !uploading\) onClose\(\)/)

// Batch informa o upload local ao workspace e limpa no unmount.
assert.match(batch, /onLocalWorkStateChange\?: \(state: \{ uploading: boolean; pending: number \}\) => void/)
assert.match(batch, /uploading: open && uploadingVideo, pending: open && uploadingVideo \? 1 : 0/)
assert.match(batch, /useEffect\(\(\) => \(\) => onLocalWorkStateChange\?\.\(\{ uploading: false, pending: 0 \}\)/)
assert.match(list, /onLocalWorkStateChange=\{onLocalWorkStateChange\}/)
assert.match(manager, /detailWork\.uploading \|\| listWork\.uploading/)
assert.match(manager, /pending: detailWork\.pending \+ listWork\.pending/)
assert.match(detail, /quickCampaignWork/)
assert.match(detail, /const localUploading = creativeBusy \|\| quickCampaignWork\.uploading/)
assert.match(detail, /const localPending = creativePending \+ quickCampaignWork\.pending/)

// Conversão protege fechamento local, sem transformar job durável em upload local.
assert.match(launcher, /const localUploadBusy = uploadingCount > 0/)
assert.match(launcher, /busy=\{submitting \|\| localUploadBusy\}/)
assert.match(launcher, /onClick=\{requestClose\} disabled=\{submitting \|\| localUploadBusy\}/)
assert.match(launcher, /Fechar esta janela não cancela a criação\. A fila continua no servidor\./)
assert.match(launcher, /onSmartPlus\} disabled=\{submitting \|\| localUploadBusy\}/)
assert.match(launcher, /onSpark\} disabled=\{submitting \|\| localUploadBusy\}/)
assert.match(smart, /busy=\{submitting \|\| uploading \|\| coverUploading\}/)

// Copy distingue upload ativo de retry/erro pendente.
assert.match(view, /type CatalogLocalWorkState = \{ uploading: boolean; pending: number \}/)
assert.match(view, /Há vídeos sendo enviados nesta área do Catálogo/)
assert.match(view, /Há envios locais pendentes ou com falha/)
assert.match(view, /opções locais de tentar novamente/)
assert.doesNotMatch(view, /catalogUploadState/)

// Back/Forward preserva a pilha real: restaura via go(), não sobrescreve target.
const popStart = view.indexOf('const handlePopState =')
const popEnd = view.indexOf("window.addEventListener('popstate'", popStart)
const popBody = view.slice(popStart, popEnd)
assert.ok(popStart >= 0 && popEnd > popStart)
assert.match(view, /roiAdsHistoryIndex/)
assert.match(popBody, /const delta = targetIndex - historyIndexRef\.current/)
assert.match(popBody, /window\.history\.go\(-delta\)/)
assert.doesNotMatch(popBody, /replaceState/)
assert.match(view, /allowNextPopRef\.current = true[\s\S]*window\.history\.go\(historyNavigation\.delta\)/)
assert.doesNotMatch(view.slice(view.indexOf('onConfirm={() => {', popEnd)), /commitTabChange\(historyNavigation\.target/)
assert.match(view, /requestTabChangeRef\.current\(value, 'tour'\)/)

// Alertas levam ao controle responsável, nunca para Segurança.
assert.match(inbox, /onOpenAlerts/)
assert.doesNotMatch(inbox, /onGoAutomations/)
assert.match(view, /function openPerformanceAlerts\(\)/)
assert.match(view, /onOpenAlerts=\{openPerformanceAlerts\}/)
const automationInbox = view.slice(view.indexOf('NeedsYouInbox key={`NeedsYouInbox:${concreteAdvertiser}`'), view.indexOf('<AutomationPanel', view.indexOf('NeedsYouInbox key={`NeedsYouInbox:${concreteAdvertiser}`')))
assert.doesNotMatch(automationInbox, /openOps\('safety'\)/)
assert.match(automation, /focusAlertsRequest\?: number/)
assert.match(automation, /setAlertsExpanded\(true\)/)
assert.match(automation, /scrollIntoView\(\{ behavior: 'smooth', block: 'center' \}\)/)
assert.match(automation, /alertsButtonRef\.current\?\.focus\(\{ preventScroll: true \}\)/)

// Profitability recebe timezone contextual, explicita a origem e mantém Overview/ROAS fora do escopo.
assert.match(magic, /advertiserTimeZone: string/)
assert.match(magic, /calendarTimeZone: advertiserTimeZone/)
assert.match(magic, /calendarSource\?: 'advertiser' \| 'advertiser_context' \| 'account_fallback' \| 'account'/)
assert.match(magic, /Fuso TikTok indisponível · período calculado em/)
assert.match(magic, /Período no fuso da conta TikTok/)
const profitabilityStart = routes.indexOf("app.get('/api/ads/profitability'")
const profitabilityEnd = routes.indexOf('// V11 — auditoria', profitabilityStart)
const profitabilityRoute = routes.slice(profitabilityStart, profitabilityEnd)
assert.match(profitabilityRoute, /advertiserLookupTimeZone = validateTimeZone/)
assert.match(profitabilityRoute, /advertiserContextTimeZone = validateTimeZone\(q\.calendarTimeZone\)/)
assert.match(profitabilityRoute, /calendarSource = 'advertiser'/)
assert.match(profitabilityRoute, /calendarSource = 'advertiser_context'/)
assert.match(profitabilityRoute, /calendarSource = 'account_fallback'/)
assert.match(profitabilityRoute, /timeZone: effectiveTimeZone/)
assert.match(profitabilityRoute, /calendarSource,/)
assert.doesNotMatch(overviewApi, /calendarTimeZone|calendar=advertiser/)
const roasStart = routes.indexOf("app.get('/api/ads/roas'")
const roasEnd = roasStart >= 0 ? routes.indexOf("app.get('", roasStart + 10) : -1
const roasRoute = roasStart >= 0 ? routes.slice(roasStart, roasEnd > roasStart ? roasEnd : roasStart + 5000) : ''
assert.doesNotMatch(roasRoute, /calendarTimeZone|calendarSource/)
assert.doesNotMatch(profitEngine, /calendarSource|calendarTimeZone/)

console.log('[OK] TikTok Ads V16.9 — estado local, histórico, alertas e origem do timezone coerentes.')
