'use strict'

const assert = require('assert')
const fs = require('fs')
const path = require('path')

const root = path.join(__dirname, '..')
const dashboard = path.join(root, 'dashboard')
const read = rel => fs.readFileSync(path.join(dashboard, rel), 'utf8')

const period = read('lib/overview-period.tsx')
const calendar = read('components/shell/overview-calendar.tsx')
const overview = read('components/overview/overview-view.tsx')
const metrics = read('components/overview/overview-metrics.tsx')
const funnel = read('components/funnel/funnel-view.tsx')
const activity = read('components/activity/activity-view.tsx')
const ads = read('components/ads/tiktok-ads-view.tsx')
const adsContext = read('components/ads/context-bar.tsx')
const topnav = read('components/shell/topnav.tsx')
const header = read('components/shell/header.tsx')
const hero = read('components/overview/hero-globe.tsx')
const globe = read('components/geo/globe.tsx')
const api = read('lib/api.ts')
const css = read('app/dashboard-refinement.css')
const adsRoutes = fs.readFileSync(path.join(root, 'ads-routes.js'), 'utf8')

assert.match(period, /roi:dashboard:period/, 'período deve usar chave global')
assert.match(period, /roi:period-change/, 'mudança do período deve ser propagada no shell')
assert.doesNotMatch(calendar, /pathname\s*!==\s*['"]\/["']/, 'calendário não pode ser exclusivo da Visão Geral')
assert.match(calendar, /Período global da dashboard/, 'calendário deve comunicar escopo global')

assert.match(overview, /useOverviewPeriod\(\)/, 'Visão Geral deve consumir período global')
assert.match(overview, /mutateStats\(\)/, 'troca de período deve revalidar dados da Visão Geral')
assert.match(funnel, /useOverviewPeriod\(\)/, 'Funil deve consumir período global')
assert.doesNotMatch(funnel, /<PeriodPicker/, 'Funil não deve manter seletor local concorrente')
assert.match(activity, /useOverviewPeriod\(\)/, 'Atividade deve consumir período global')
assert.match(activity, /periodEvents/, 'Atividade deve filtrar eventos pela janela global')
assert.match(ads, /useOverviewPeriod\(\)/, 'TikTok Ads deve consumir período global')
assert.doesNotMatch(adsContext, /onRangeDays|rangeDays/, 'TikTok Ads não deve manter calendário local concorrente')

assert.match(metrics, /title="Lucro"/, 'Visão Geral deve exibir Lucro')
assert.match(metrics, /signDisplay:\s*'always'/, 'Lucro deve manter sinal positivo ou negativo')
assert.match(api, /useAdsProfitability/, 'Lucro deve consumir rentabilidade real quando disponível')
assert.match(metrics, /title="Conversão"/, 'Conversão geral deve permanecer na Visão Geral')
assert.match(metrics, /title="ROAS"/, 'ROAS deve permanecer na Visão Geral')
assert.match(adsRoutes, /spend\s*>\s*0\s*\?[^\n]+:\s*0/, 'ROAS sem investimento deve resultar em zero em vez de indisponível')

assert.doesNotMatch(topnav, /label:\s*'Vendas'/, 'Vendas deve sair do menubar')
assert.doesNotMatch(topnav, /WorkspaceMenu/, 'contas de anúncio devem sair do menubar')
assert.doesNotMatch(header, /WorkspaceMenu/, 'header não deve conter seletor de contas de anúncio')
assert.match(hero, /observatory-live-compact/, 'visitantes ao vivo deve usar representação compacta')
assert.match(globe, /toggleRotation/, 'controle de pausa deve usar transição suave de rotação')
assert.match(globe, /duration:\s*560/, 'movimentos de câmera devem usar duração suavizada')

assert.match(css, /grid-template-columns:\s*1fr 1fr;[\s\S]*\.observatory-live\s*\{[\s\S]*grid-column:\s*1\s*\/\s*-1/, 'Top países e Compras devem compartilhar colunas iguais, com Ao vivo compacto acima')
assert.match(css, /section-tabs--ads[\s\S]*min-width:\s*118px/, 'subabas de TikTok devem ter largura padronizada')
assert.match(css, /context-nav__item[\s\S]*min-width:\s*118px/, 'subabas de Rastreamento devem ter largura padronizada')
assert.match(css, /tiktok-tabs-row[\s\S]*grid-template-columns:\s*minmax\(0, 1fr\) auto minmax\(0, 1fr\)/, 'subabas de TikTok devem ficar matematicamente centralizadas')

console.log('dashboard-global-period-v10: OK')
