'use strict'

const fs = require('fs')
const path = require('path')
const assert = require('assert')

const root = path.join(__dirname, '..')
const launcher = fs.readFileSync(path.join(root, 'dashboard/components/ads/universal-launcher-dialog.tsx'), 'utf8')
const smart = fs.readFileSync(path.join(root, 'dashboard/components/ads/smart-plus-create-dialog.tsx'), 'utf8')
const spark = fs.readFileSync(path.join(root, 'dashboard/components/ads/spark-ad-dialog.tsx'), 'utf8')
const saved = fs.readFileSync(path.join(root, 'dashboard/components/ads/saved-videos.tsx'), 'utf8')
const market = fs.readFileSync(path.join(root, 'dashboard/components/ads/market-selector.tsx'), 'utf8')
const types = fs.readFileSync(path.join(root, 'dashboard/lib/types.ts'), 'utf8')
const css = fs.readFileSync(path.join(root, 'dashboard/app/task-dialogs.css'), 'utf8')

assert(launcher.includes('Conversão (CBO)'), 'launcher deve chamar o formato de Conversão (CBO)')
assert(!launcher.includes('<strong>Direta</strong>'), 'Direta não deve continuar como nome principal')
assert(launcher.includes("apiSend<AdsBulkStartResponse>('/api/ads/bulk'"), 'múltiplos vídeos devem continuar usando /api/ads/bulk')
assert(launcher.includes('Number(budget) * items.length'), 'revisão deve calcular gasto total potencial pelo número de campanhas')
assert(launcher.includes('Criar ${items.length} campanhas pausadas'), 'CTA bulk deve deixar claro que as campanhas nascem pausadas')
assert(launcher.includes('items.map((it)'), 'bulk deve continuar criando um item por vídeo')
assert(launcher.includes('Nome da campanha'), 'nomes dos itens devem ser editáveis no launcher')
assert(launcher.includes('appearance="creation"'), 'controles compartilhados devem usar variante visual específica da criação')
assert(launcher.includes('Pixel da conta'), 'Pixel deve aparecer como pré-requisito/contexto central')
assert(!launcher.includes('input-neon'), 'launcher refinado não deve usar input neon')
assert(launcher.includes('Fila temporariamente pausada pelo TikTok'), 'fila deve explicar rate limit temporário')
assert(launcher.includes('Fechar esta janela não cancela a criação'), 'fila durável deve ser explicada ao usuário')
assert(launcher.includes('retryAt'), 'UI deve apresentar retry por item quando disponível')
assert(launcher.includes("'/api/ads/create/preflight'"), 'preflight da Conversão deve ser preservado')

assert(smart.includes('O TikTok automatiza público, lance e distribuição'), 'Smart+ deve explicar claramente a automação do TikTok')
assert(smart.includes('Orçamento total'), 'Smart+ deve preservar orçamento total')
assert(smart.includes('Data de término'), 'Smart+ deve preservar término')
assert(smart.includes('não é orçamento diário configurado'), 'média diária Smart+ não pode parecer orçamento diário')
assert(!smart.includes('Smart+ automatizada</strong>'), 'cards conceituais antigos do topo devem ser removidos')
assert(!smart.includes('input-neon'), 'Smart+ refinado não deve usar input neon')
assert(smart.includes("'/api/ads/smart-plus'"), 'endpoint Smart+ deve ser preservado')

assert(spark.includes('Nada é selecionado automaticamente'), 'Spark deve explicitar escolha manual de identidade/post')
assert(spark.includes('setIdentityKey(key)'), 'identidade Spark deve continuar escolhida pelo usuário')
assert(spark.includes('setItemId(v.itemId)'), 'post Spark deve continuar escolhido pelo usuário')
assert(spark.includes('resgate o Spark Code no TikTok Ads Manager'), 'Spark Code deve ser explicado sem input falso')
assert(spark.includes("'/api/ads/boost'"), 'endpoint Spark deve ser preservado')
assert(!spark.includes('input-neon'), 'Spark refinado não deve usar input neon')

assert(saved.includes("appearance?: 'default' | 'creation'"), 'biblioteca deve preservar default e oferecer variante de criação')
assert(saved.includes('Escolher da biblioteca'), 'biblioteca deve ficar descobrível')
assert(market.includes("appearance?: 'default' | 'creation'"), 'MarketSelector deve preservar default e oferecer variante de criação')
assert(types.includes('attempts?: number'), 'tipo bulk deve expor tentativas já retornadas pelo backend')
assert(types.includes('retryAt?: string'), 'tipo bulk deve expor retryAt')
assert(types.includes('pausedUntil?: string | null'), 'tipo bulk deve expor pausa da fila')
assert(css.includes('.tiktok-create-flow .launch-section-card'), 'novos estilos devem estar escopados ao fluxo TikTok')
assert(css.includes('.tiktok-create-flow .launch-review'), 'revisão quiet deve estar escopada ao fluxo TikTok')

console.log('[OK] TikTok Ads V16.2 — criação coerente, autoexplicativa, fila transparente e contratos preservados.')
