'use strict'

const fs = require('fs')
const path = require('path')
const assert = require('assert')

const root = path.join(__dirname, '..')
const globals = fs.readFileSync(path.join(root, 'dashboard/app/globals.css'), 'utf8')
const refinement = fs.readFileSync(path.join(root, 'dashboard/app/dashboard-refinement.css'), 'utf8')
const toaster = fs.readFileSync(path.join(root, 'dashboard/components/shell/toaster.tsx'), 'utf8')
const pushSound = fs.readFileSync(path.join(root, 'dashboard/components/shell/push-sound.tsx'), 'utf8')
const pushCard = fs.readFileSync(path.join(root, 'dashboard/components/config/web-push-card.tsx'), 'utf8')
const pushClient = fs.readFileSync(path.join(root, 'dashboard/lib/web-push.ts'), 'utf8')
const notifyPrefs = fs.readFileSync(path.join(root, 'dashboard/lib/notify-prefs.ts'), 'utf8')
const sw = fs.readFileSync(path.join(root, 'dashboard/public/sw.js'), 'utf8')
const manifest = fs.readFileSync(path.join(root, 'dashboard/app/manifest.ts'), 'utf8')
const copy = fs.readFileSync(path.join(root, 'notify-copy.js'), 'utf8')
const bell = fs.readFileSync(path.join(root, 'dashboard/components/shell/notification-bell.tsx'), 'utf8')
const activity = fs.readFileSync(path.join(root, 'dashboard/components/activity/activity-view.tsx'), 'utf8')
const configView = fs.readFileSync(path.join(root, 'dashboard/components/config/config-view.tsx'), 'utf8')
const companionCard = fs.readFileSync(path.join(root, 'dashboard/components/config/iphone-companion-card.tsx'), 'utf8')

assert(globals.includes('.roi-toast-in') && globals.includes('roiAttentionIn'), 'micro motion deve ficar restrito a feedback e atenção')
assert(globals.includes('@media (prefers-reduced-motion: reduce)') && globals.includes("html[data-anim='off'] .roi-toast-in"), 'novos efeitos devem respeitar redução de movimento do SO e da conta')
assert(globals.includes('.anim-shake') && globals.includes('.toast-life'), 'feedback transitório também deve respeitar redução de movimento')
assert(refinement.includes('navbar-popover-in 140ms') && !refinement.includes('translateY(-4px) scale(.985)'), 'popover deve entrar curto sem escalar texto')
assert(refinement.includes('dashboard-page-enter 220ms') && refinement.includes('.dashboard-main > *'), 'entrada curta deve acontecer dentro da dashboard')
assert(refinement.includes("html[data-anim='off'] .refined-dashboard .dashboard-main > *"), 'entrada de página deve respeitar reduzir animações')
assert(toaster.includes('roi-toast-in') && !toaster.includes('anim-pop-spring pointer-events-auto'), 'toast deve usar uma única entrada curta')
assert(toaster.includes('animationDuration: `${t.duration}ms`'), 'barra de vida do toast deve acompanhar a duração real')
assert(activity.includes('seenEventIdsRef') && activity.includes('activity-sale-arrival'), 'somente vendas novas devem receber feedback visual ao vivo')
assert(globals.includes('.activity-event-row.activity-sale-arrival') && !globals.includes(".activity-event-row[data-event-type='sale'] {\n  animation:"), 'histórico de vendas não deve reanimar a cada render')
assert(globals.includes('@keyframes roiSaleArrival') && globals.includes("html[data-anim='off'] .activity-sale-arrival::after"), 'destaque de venda deve ser curto e respeitar redução de movimento')
assert(globals.includes('@keyframes roiSalePulse') && globals.includes("data-roi-sale-pulse='on'"), 'venda em foreground deve ter um único pulso dentro da dashboard')

assert(pushClient.includes("platform: 'ios' | 'other'") && pushClient.includes('iOS/iPadOS 16.4'), 'detecção deve explicar requisito real do Web Push no iPhone')
assert(pushClient.includes("navigator.platform === 'MacIntel' && navigator.maxTouchPoints > 1"), 'detecção iPadOS deve cobrir user agent desktop')
assert(manifest.includes('id: "/dashboard"') && manifest.includes('display: "standalone"'), 'PWA deve ter identidade estável e modo standalone')
assert(pushCard.includes('Sons no painel aberto') && pushCard.includes('O iOS controla som, Foco e estilo do alerta'), 'configuração deve separar som local do comportamento do iPhone')
assert(pushCard.includes("key: 'reports'") && pushCard.includes('Relatórios executivos'), 'relatórios devem ter preferência própria no push')
assert(pushCard.includes('Ouvir som de venda') && pushCard.includes('playSaleSound'), 'usuário deve conseguir ouvir a assinatura sonora da venda')
assert(configView.includes('<IPhoneCompanionCard />'), 'conectividade nativa do iPhone deve aparecer em Alertas')
assert(configView.includes('/api/reports/daily/preview') && configView.includes('Ver prévia real'), 'resumo diário deve permitir conferir o conteúdo real antes do agendamento')
assert(companionCard.includes('/api/companion/status') && companionCard.includes('/api/companion/token'), 'pareamento iPhone deve usar endpoints dedicados e não o token público')
assert(pushCard.includes('Ajustes → Notificações → ROI-NADOS'), 'permissão negada no iPhone deve ter recuperação clara')
assert(pushCard.includes('setSupport(checkSupport())'), 'estado de permissão deve ser reavaliado depois do prompt')
assert(notifyPrefs.includes('roi-sound-enabled') && notifyPrefs.includes('getSoundMasterEnabled()'), 'som local deve poder ser desligado por aparelho')
assert(pushSound.includes("document.visibilityState !== 'visible'"), 'WebAudio não deve duplicar alerta quando dashboard está em background')
assert(pushSound.includes("toast.success(title || 'Venda aprovada'") && pushSound.includes("eventName === 'daily'"), 'push em foreground deve virar feedback profissional dentro da dashboard')
assert(pushSound.includes('dataset.roiSalePulse') && pushSound.includes("roi:foreground-notification"), 'feedback de venda deve animar o painel e avisar métricas em tempo real')
assert(sw.includes('type: "roi-notification"') && sw.includes('priority: data.priority || "normal"'), 'service worker deve entregar contexto rico ao foreground')
assert(sw.includes('if (hasVisibleClient)') && sw.includes('else {\n      promises.push(self.registration.showNotification'), 'dashboard visível deve usar feedback interno sem duplicar banner do sistema')
const saleAlerts = fs.readFileSync(path.join(root, 'dashboard/lib/sale-alerts.ts'), 'utf8')
assert(!saleAlerts.includes('Math.random() * 2 - 1'), 'som de venda não deve usar ruído branco mecânico')
assert(saleAlerts.includes("freq: 880") && saleAlerts.includes("freq: 1320") && saleAlerts.includes("freq: 1760"), 'som de venda deve usar a assinatura tonal curta do ROI-NADOS')
assert(!fs.existsSync(path.join(root, 'dashboard/public/cash.mp3')), 'asset legado de áudio não utilizado deve permanecer removido')

assert(sw.includes('data.badge === true') && sw.includes('self.navigator.setAppBadge()'), 'push relevante deve atualizar badge do app instalado')
assert(sw.includes('self.navigator.clearAppBadge()'), 'toque na notificação deve limpar badge do app')
assert(sw.includes('omitimos \`silent\` para respeitar o padrão do aparelho/Foco') && sw.includes('options.silent = true'), 'service worker deve respeitar o aparelho em background')
assert(sw.includes('hasVisibleClient || data.event === "daily"'), 'brief diário deve permanecer silencioso também em background')
assert(bell.includes('clearAppBadge') && bell.includes('abre a central'), 'central de notificações deve limpar o badge ao ser revisada')

assert(copy.includes("login: '/dashboard/config?tab=security'"), 'login deve abrir Segurança')
assert(copy.includes("ads_rejected: '/dashboard/ads/tiktok?tab=automation'"), 'reprovação deve abrir Automações')
assert(copy.includes("ads_breaker: '/dashboard/ads/tiktok?tab=automation'"), 'circuit breaker deve abrir Automações')
assert(copy.includes("ads_breaker: 'alert'"), 'circuit breaker deve usar feedback sonoro compatível com severidade')
assert(copy.includes("ads_cap: '/dashboard/ads/tiktok?tab=automation'"), 'limite de automação deve abrir Automações')
assert(copy.includes("test: '/dashboard/config?tab=notifications'"), 'teste deve voltar à configuração de Alertas')

console.log('[OK] V16.25 — micro motion, iPhone Web Push, badge e sons locais coerentes.')
