'use strict'

const fs = require('fs')
const path = require('path')
const assert = require('assert')

const root = path.join(__dirname, '..')
const tree = fs.readFileSync(path.join(root, 'dashboard/components/ads/campaign-tree.tsx'), 'utf8')
const drawer = fs.readFileSync(path.join(root, 'dashboard/components/ads/campaign-drawer.tsx'), 'utf8')
const editor = fs.readFileSync(path.join(root, 'dashboard/components/ads/ad-edit-dialog.tsx'), 'utf8')

assert(tree.includes('Estrutura rápida'), 'expansão deve ser apresentada como estrutura rápida')
assert(tree.includes('Abrir Central da campanha'), 'expansão deve encaminhar para a Central')
assert(!tree.includes("import { CampaignMetricGrid } from './campaign-metric-grid'"), 'expansão não deve carregar a grade completa de métricas')
assert(!tree.includes('Passe o mouse para reproduzir'), 'preview não pode depender de hover')
assert(tree.includes('controls muted playsInline'), 'preview de vídeo deve ser utilizável por toque')
assert(tree.includes('Destino definido pelos produtos do catálogo.'), 'Product Link deve explicar a origem do destino')

assert(drawer.includes("type SectionKey = 'overview' | 'structure' | 'history'"), 'Central mantém Resultado/Estrutura/Histórico')
assert(drawer.includes("sectionTab('overview', 'Resultado')"), 'Resultado deve usar tab textual')
assert(drawer.includes("sectionTab('structure', 'Estrutura')"), 'Estrutura deve usar tab textual')
assert(drawer.includes("sectionTab('history', 'Histórico')"), 'Histórico deve usar tab textual')
assert(drawer.includes('appearance="quiet"'), 'ações sensíveis devem usar ConfirmDialog quiet')
assert(drawer.includes('Ao ativar, a campanha poderá começar a gastar.'), 'ativação deve comunicar risco financeiro')
assert(drawer.includes("campaign.status === 'active'"), 'pausa e ativação continuam condicionadas ao status real')
assert(drawer.includes("setCampaignStatus('paused')"), 'pausa continua imediata')
assert(drawer.includes('setActivationOpen(true)'), 'ativação deve abrir confirmação antes de executar')
assert(drawer.includes('realRevenue / totals.spend'), 'ROAS real deve aceitar receita zero quando gasto existe')
assert(drawer.includes("analyticsLoaded ? fmtSpend(totals.spend, ccy) : '—'"), 'loading não pode aparecer como falso zero de gasto')
assert(drawer.includes('Métricas secundárias'), 'métricas detalhadas devem permanecer disponíveis na Central')
assert(drawer.includes('CBO · controlado no nível da campanha.'), 'Central deve explicar CBO')
assert(drawer.includes('ABO · cada conjunto controla o próprio orçamento.'), 'Central deve explicar ABO')
assert(drawer.includes('entityId={group.platformAdSetId}'), 'ABO deve ser editável no conjunto')
assert(drawer.includes('Reprovado pelo TikTok'), 'reprovação deve permanecer visível em contexto')
assert(drawer.includes('humanAuditAction'), 'histórico deve humanizar códigos conhecidos')
assert(!drawer.includes('StatusPill'), 'Central V16.1 não deve voltar a pills de status')
assert(!drawer.includes('GlassCard'), 'Central V16.1 deve evitar card wall e superfícies aninhadas')
assert(!drawer.includes('linearGradient'), 'gráfico não deve usar gradient decorativo')

assert(editor.includes('Somente os campos alterados serão enviados ao TikTok.'), 'editor deve explicar o patch parcial')
assert(editor.includes('Alterações podem iniciar uma nova revisão do anúncio.'), 'editor deve explicar impacto de revisão')
assert(editor.includes('hasChanges'), 'Salvar deve depender de alterações reais')
assert(editor.includes('disabled={saving || linkInvalid || !hasChanges}'), 'Salvar deve ficar desabilitado sem mudanças')
assert(!editor.includes('input-neon'), 'editor não deve usar input neon')
assert(editor.includes('md:grid-cols-2'), 'editor deve manter uma coluna em telas estreitas')
assert(editor.includes('O destino deste anúncio é definido nos produtos do catálogo.'), 'Product Link deve ser autoexplicativo no editor')

console.log('[OK] TikTok Ads V16.1 — estrutura rápida, Central editorial, autonomia visual e guardrails preservados.')
