'use strict'

const fs = require('fs')
const path = require('path')
const assert = require('assert')

const root = path.join(__dirname, '..')
const tree = fs.readFileSync(path.join(root, 'dashboard/components/ads/campaign-tree.tsx'), 'utf8')
const provider = fs.readFileSync(path.join(root, 'ads-provider.js'), 'utf8')
const types = fs.readFileSync(path.join(root, 'dashboard/lib/types.ts'), 'utf8')
const adsView = fs.readFileSync(path.join(root, 'dashboard/components/ads/tiktok-ads-view.tsx'), 'utf8')
const automation = fs.readFileSync(path.join(root, 'dashboard/components/ads/automation-panel.tsx'), 'utf8')
const magicOps = fs.readFileSync(path.join(root, 'dashboard/components/ads/magic-ops-panel.tsx'), 'utf8')
const catalogList = fs.readFileSync(path.join(root, 'dashboard/components/ads/catalog-list.tsx'), 'utf8')

assert(tree.includes("useState<'campaign' | 'adgroup' | 'ad'>('campaign')"), 'workspace deve preservar os três níveis operacionais')
assert(tree.includes("'Campanhas', campaigns.length") && tree.includes("'Conjuntos', adGroupCount") && tree.includes("'Anúncios', adCount"), 'seletor deve expor campanhas, conjuntos e anúncios')
assert(tree.includes('selectedEntities') && tree.includes('applyEntityBulkStatus'), 'conjuntos e anúncios devem suportar seleção e status em lote')
assert(tree.includes("'Buscar anúncio, copy, conjunto ou campanha…'"), 'busca de anúncios deve procurar também por contexto e copy')
assert(tree.includes('function EntityToolbar') && tree.includes("'Maior gasto'") && tree.includes("'Maior CTR'") && tree.includes("'Mais conversões'"), 'conjuntos e anúncios devem ter ordenação operacional própria')
assert(tree.includes('const commandCenter = useMemo') && tree.includes('Propostas ROI NADOS') && tree.includes('Precisa de atenção'), 'workspace deve expor command center contextual')
assert(tree.includes('spentNoSales') && tree.includes('Com gasto e sem venda real'), 'KPI de atenção em campanhas deve corresponder ao filtro acionado')
assert(tree.includes('function sourceWeightedCtr'), 'CTR agregado de conjuntos/anúncios deve ser ponderado por impressões')
assert(tree.includes("'issues', 'Atenção'") && tree.includes('entityStatusMatches'), 'workspace deve filtrar entidades por estado operacional')
assert(tree.includes("entityLevel === 'campaign' && selected.size > 0"), 'barra em lote de campanha não deve vazar para outras visões')
assert(tree.includes('entityLabel="conjunto"') && tree.includes('entityLabel="anúncio"'), 'toggles independentes devem identificar o nível correto')
assert(tree.includes('Central do criativo') && tree.includes('setCreativeInspect'), 'anúncio deve abrir central contextual do criativo')
assert(tree.includes('Propostas ROI NADOS') && tree.includes('Autonomia'), 'cockpit deve concentrar propostas e estado real da automação')
assert(tree.includes('function creativeSignal') && tree.includes("'Aprendendo'") && tree.includes("'Convertendo'") && tree.includes("'Atenção'"), 'anúncios devem expor sinais conservadores baseados em métricas reais')
assert(!tree.includes("'Fadiga detectada'"), 'UI não deve inventar fadiga sem série temporal')
assert(!adsView.includes('aria-label="Resumo das campanhas"'), 'TikTok Ads não deve duplicar KPIs acima do cockpit contextual')
assert((adsView.match(/<NeedsYouInbox/g) || []).length === 1, 'aprovações devem ter uma única superfície completa na aba Automações')
assert(adsView.includes('Custos, análise, vídeos e proteção') && !adsView.includes('>Mais ferramentas<'), 'área avançada deve dizer claramente o que contém')
assert(automation.includes('Aplicando automaticamente') && automation.includes('Revisar segurança'), 'automação deve explicar estado real e oferecer recuperação contextual')
assert(!magicOps.includes('/api/cloak/blocks') && !magicOps.includes('Bloqueios de tráfego'), 'TikTok Ads não deve misturar controles do Cloaker')
assert(magicOps.includes('Fila operacional') && magicOps.includes('Aguardando retomada automática.'), 'fila TikTok deve permanecer visível com estado verdadeiro')
assert(catalogList.includes('nextCatalogAction') && catalogList.includes('Catálogos prontos para anunciar'), 'catálogo deve orientar a próxima ação sem score artificial')
assert(tree.includes('resetEntityFilters') && tree.includes('Nenhum anúncio corresponde aos filtros.'), 'filtros de entidade devem ser recuperáveis')

assert(provider.includes('async function resolveVideoCreativeAssets'), 'provider deve enriquecer assets de vídeo')
assert(provider.includes("'get_tiktok_video_info'"), 'resolver deve usar metadados canônicos do TikTok')
assert(provider.includes('offset += 50'), 'resolver deve agrupar IDs e evitar N+1 por anúncio')
assert(provider.includes("videoAssets.get(ad.videoId)?.coverUrl"), 'árvore deve usar capa resolvida')
assert(provider.includes('const smartVideoIds = ads.map'), 'Smart+ também deve resolver previews em lote')
assert(!provider.includes("'tiktok:video:' + ad.videoId"), 'árvore não pode voltar a publicar pseudo-URL de vídeo')
assert(!provider.includes("'tiktok:image:' + ad.imageIds[0]"), 'árvore não pode voltar a publicar pseudo-URL de imagem')

assert(types.includes('videoId?: string') && types.includes('imageIds?: string[]'), 'contrato deve preservar IDs canônicos dos assets')

console.log('[OK] TikTok Ads V16.24 — workspace por entidade, operações em lote, central do criativo e preview em lote.')
