'use strict'

const assert = require('node:assert/strict')
const fs = require('node:fs')

function read(path) {
  return fs.readFileSync(path, 'utf8')
}

const nav = read('dashboard/lib/navigation.ts')
const view = read('dashboard/components/insights/insights-view.tsx')
const subnav = read('dashboard/components/shell/subnav.tsx')
const header = read('dashboard/components/shell/header.tsx')
const page = read('dashboard/app/(dashboard)/insights/page.tsx')
const layout = read('dashboard/app/(dashboard)/layout.tsx')
const anomalies = read('dashboard/lib/insight-anomalies.ts')
const anomaliesPanel = read('dashboard/components/insights/anomalies-panel.tsx')
const opportunities = read('dashboard/lib/insight-opportunities.ts')
const opportunitiesPanel = read('dashboard/components/insights/opportunities-panel.tsx')

assert.match(nav, /id: 'insights'/)
assert.match(nav, /label: 'Inteligência'/)
assert.match(nav, /\/insights\?tab=funnel/)
assert.match(nav, /\/insights\?tab=sources/)
assert.match(nav, /\/insights\?tab=opportunities/)
assert.match(nav, /\/insights\?tab=anomalies/)
assert.match(nav, /\/insights\?tab=quality/)

assert.match(view, /useOverviewAnalytics/)
assert.match(view, /useOverviewHealth/)
assert.match(view, /type InsightTab = 'performance' \| 'funnel' \| 'sources' \| 'opportunities' \| 'anomalies' \| 'quality'/)
assert.match(view, /Maior perda:/)
assert.match(view, /Campanhas identificadas/)
assert.match(view, /Compras rastreadas/)
assert.match(view, /Próximas ações/)
assert.match(view, /<OpportunitiesPanel/)
assert.match(view, /<AnomaliesPanel/)
assert.match(anomalies, /buildInsightAnomalies/)
assert.match(anomalies, /traffic-without-sales/)
assert.match(anomalies, /revenue-drop/)
assert.match(anomalies, /conversion-drop/)
assert.match(anomalies, /purchase-coverage/)
assert.match(anomaliesPanel, /Radar automático/)
assert.match(opportunities, /buildInsightOpportunities/)
assert.match(opportunities, /revenue-growth/)
assert.match(opportunities, /campaign-growth/)
assert.match(opportunitiesPanel, /Sinais positivos/)

assert.match(subnav, /useSearchParams/)
assert.match(subnav, /group\.id === 'insights'/)
assert.match(header, /pathname\.startsWith\('\/insights'\)/)
assert.match(page, /<InsightsView \/>/)
assert.match(layout, /<Suspense fallback=\{null\}><SubNav \/><\/Suspense>/)

console.log('dashboard intelligence v16.24: ok')
