'use strict'
const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')
const root = path.resolve(__dirname, '..')
const read = (p) => fs.readFileSync(path.join(root, p), 'utf8')

const automation = read('dashboard/components/ads/automation-panel.tsx')
const pilots = read('dashboard/components/ads/pilots-panel.tsx')
const inbox = read('dashboard/components/ads/needs-you-inbox.tsx')
const rejection = read('dashboard/components/ads/rejection-inbox.tsx')
const logs = read('dashboard/components/ads/rules-log-list.tsx')
const magic = read('dashboard/components/ads/magic-ops-panel.tsx')
const view = read('dashboard/components/ads/tiktok-ads-view.tsx')

assert.doesNotMatch(automation, /Autonomia<\/p>|Regras ativas<\/p>|Última atividade<\/p>/)
assert.match(view, /appearance="automation"/)
assert.match(view, /appearance="embedded"/)
assert.doesNotMatch(inbox, /O robô sugere/)
assert.match(inbox, /beforeState/)
assert.match(inbox, /afterState/)
assert.match(inbox, /Aprovar aumento de orçamento\?/)
assert.match(inbox, /appearance="quiet"/)
assert.match(automation, /Só avisar|Somente monitorando/)
assert.match(pilots, /As regras monitoram as campanhas e criam propostas/)
assert.match(pilots, /As regras ativas podem pausar campanhas e ajustar orçamentos/)
assert.match(automation, /Executar avaliação agora\?/)
assert.match(automation, /appearance="quiet"/)
assert.match(pilots, /Aplicar ajustes/)
assert.match(pilots, /O que será aplicado/)
assert.match(pilots, /autonomy === 'notify'/)
assert.match(rejection, /Recurso automático de anúncios Smart\+/)
assert.match(rejection, /Enviar recursos Smart\+ automaticamente\?/)
assert.match(automation, /Alterações não salvas/)
assert.doesNotMatch(logs, /rounded-full px-1\.5 py-0\.5/)
assert.doesNotMatch(automation, /input-neon/)
assert.match(automation, /automaticBlockedReason/)
assert.match(automation, /Remover esta regra\?/)
assert.match(magic, /Estes custos padrão se aplicam à conta ROI-NADOS/)
assert.match(magic, /Salvar origem/)
assert.match(magic, /Sincronizar agora/)
assert.match(magic, /roi_ads_widget_order/)
assert.match(magic, /Organizar/)
assert.match(magic, /Remover este bloqueio\?/)

for (const file of ['ads-automation.js','ads-routes.js','ads-provider.js','ads-ops-store.js']) {
  const current = read(file)
  assert(current.length > 0, `${file} deve permanecer presente`)
}
console.log('[OK] TikTok Ads V16.4 — automações operacionais, autoexplicativas e sem backend novo.')
